# -*- coding: utf-8 -*-
"""digitalclock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YhP_IKp-UI4LI1l6T88IwAbpjrbNOaPF
"""

import tkinter as tk
import time

# Create main window
root = tk.Tk()
root.title("Modern Digital Clock")
root.geometry("520x260")
root.configure(bg="#101820")   # Dark navy background
root.resizable(True, True)

# Fonts and style
clock_font = ("Helvetica", 70, "bold")
date_font = ("Verdana", 26)
text_color = "#32CD32"   # Lime green for clock
date_color = "#E0E0E0"   # Light gray for date

# Labels
clock_label = tk.Label(root, font=clock_font, fg=text_color, bg="#101820")
clock_label.pack(pady=(25, 0))

date_label = tk.Label(root, font=date_font, fg=date_color, bg="#101820")
date_label.pack(pady=(10, 20))

# Format toggle (12h/24h)
use_24hr = True
def switch_format():
    global use_24hr
    use_24hr = not use_24hr

toggle_btn = tk.Button(root, text="Toggle 12H / 24H", command=switch_format,
                       bg="#333333", fg="white", relief="flat", padx=10, pady=5)
toggle_btn.pack()

# Update function
def update_time():
    if use_24hr:
        current_time = time.strftime("%H:%M:%S")   # 24-hour
    else:
        current_time = time.strftime("%I:%M:%S %p")  # 12-hour with AM/PM

    current_date = time.strftime("%A, %d %B %Y")  # Full date format

    clock_label.config(text=current_time)
    date_label.config(text=current_date)

    # Run this function again after 500ms
    root.after(500, update_time)

# Start the loop
update_time()
root.mainloop()